// src/dummyData.ts

export const jobs = [
  {
    id: "j1",
    title: "Frontend Developer",
    description: "Build amazing UIs.",
    requirements: "React, TypeScript",
    location: "Remote",
    jobType: "Full-time",
    experienceLevel: "Mid",
    salaryRange: "$60,000 - $80,000",
    skillsRequired: ["React", "TypeScript"],
    companyId: "c1",
    status: "approved",
    views: 123,
    createdAt: "2024-06-01",
  },
  {
    id: "j2",
    title: "Backend Developer",
    description: "Work on APIs and databases.",
    requirements: "Node.js, PostgreSQL",
    location: "Onsite",
    jobType: "Full-time",
    experienceLevel: "Senior",
    salaryRange: "$80,000 - $100,000",
    skillsRequired: ["Node.js", "PostgreSQL"],
    companyId: "c2",
    status: "pending",
    views: 45,
    createdAt: "2024-06-05",
  },
];

export const companies = [
  {
    id: "c1",
    name: "Acme Corp",
    logoUrl: "/dummy-logo.png",
    contact: "hr@acme.com",
    sector: "Technology",
    size: "100-500",
    website: "https://acme.com",
    description: "A leading tech company.",
    address: "123 Main St",
    city: "Metropolis",
    state: "State",
    country: "Country",
    userId: "2",
  },
  {
    id: "c2",
    name: "Beta Solutions",
    logoUrl: "/dummy-logo2.png",
    contact: "jobs@betasolutions.com",
    sector: "Consulting",
    size: "50-200",
    website: "https://betasolutions.com",
    description: "Consulting and IT services.",
    address: "456 Side St",
    city: "Gotham",
    state: "State",
    country: "Country",
    userId: "4",
  },
]; 